version: '3'

services:
  app:
    build:
      context: .
      args:
        - PORT=${PORT:-8000}
    container_name: vietnamese-rag-app
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - PORT=${PORT:-8000}
    volumes:
      - huggingface_cache:/app/.cache/huggingface
    restart: unless-stopped

volumes:
  huggingface_cache:
